<a href="https://colab.research.google.com/github/ricardodhuelsmann/python_bibliotecas/blob/main/Introdu%C3%A7%C3%A3o%20ao%20NumPy/2_Acessando_editando_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
###Exemplos de acesso e edição de dados

In [2]:
import numpy as np

In [26]:
'''
Para iniciar, criamos um array de duas dimensões
'''
array_1 = np.array([[0,1,2,3,4], [9,8,7,6,5]], dtype='int16')
print(array_1)
print(f'A dimensão do primeiro array é {array_1.ndim} e sua forma é {array_1.shape}.')

[[0 1 2 3 4]
 [9 8 7 6 5]]
A dimensão do primeiro array é 2 e sua forma é (2, 5).


In [6]:
'''
Para obter um determinado valor, usa-se o padrão do Python (inicia contagem em zero).
Para uma matriz de duas dimensões, passa-se os dados necessários da seguinte forma:
[linha, coluna]
'''
print(array_1[1,2]) #Obtém o valor da segunda linha, terceira coluna

7


In [27]:
'''
Agora testando array de uma única dimensão
'''
array_2 = np.array([10, 15, 20])
print(array_2)
print(f'A dimensão do segundo array é {array_2.ndim} e sua forma é {array_2.shape}.')

[10 15 20]
A dimensão do segundo array é 1 e sua forma é (3,).


In [28]:
'''
Para obter um determinado valor, no caso de uma matriz de uma dimensão,
passa-se naturalmente, a posição do elemento desejado
'''
print(array_2[0]) #Imprime o primeiro valor do array_2

10


In [31]:
'''
É possível fazer o mesmo com multidimensões
'''
array_3 = np.array([[[0,0,0], [1,1,1]], [[2,2,2], [3,3,3]]])
print(array_3)
print(f'A dimensão do terceiro array é {array_3.ndim} e sua forma é {array_3.shape}.')

[[[0 0 0]
  [1 1 1]]

 [[2 2 2]
  [3 3 3]]]
A dimensão do terceiro array é 3 e sua forma é (2, 2, 3).


In [32]:
'''
Para o caso de array multidimensional, passa-se 
informações de todas as dimensões necessárias
'''
print(array_3[1,1,2]) #Dimensão 2, linha 2 e coluna 3

3


In [33]:
'''
É possível encontrar linhas ou colunas inteiras
'''
print(array_1[0, :]) #Retorna toda a primeira linha

[0 1 2 3 4]


In [34]:
'''
Similarmente, faz-se o mesmo para colunas
'''
print(array_1[:, 0])

[0 9]


In [35]:
'''
Uma vez que se sabe localizar os elementos,
é possível alterá-los de forma similiar
'''
print('Antes de mudar:', array_2)
array_2[2]=-99
print('Depois de mudar:', array_2)

Antes de mudar: [10 15 20]
Depois de mudar: [ 10  15 -99]
