<a href="https://colab.research.google.com/github/ricardodhuelsmann/python_bibliotecas/blob/main/Introdu%C3%A7%C3%A3o%20ao%20NumPy/3_Inicializando_diferentes_tipos_de_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
###Conceitos básicos para iniciar array pré-preenchidos

In [1]:
import numpy as np

In [10]:
'''
Inicilizando uma matriz com valores 'zero'.
Usando a função 'zeros', passa-se a dimensão 
desejado, e o tipo de dados
'''
array_zeros = np.zeros(3, dtype='int32')
print(array_zeros)

[0 0 0]


In [11]:
'''
Criando uma matriz com três dimensões
'''
array_zeros_2 = np.zeros((2,3,4))
print(array_zeros_2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [12]:
'''
É possível fazer algo muito semelhante, 
com valores 'um'
'''
array_um = np.ones((2,5))
print(array_um)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
'''
Podemos também espeficiar outro valor
para preencher a matriz (função full, recebe a forma e o valor)
'''
array_especifico = np.full((3,3), 9)
print(array_especifico)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [14]:
'''
Se o objetivo for criar uma matriz 
com valores aleatórios, é possível usar 
a função 'random.rand', passando a forma desejada
'''
array_aleatorio = np.random.rand(3,2,4)
print(array_aleatorio)

[[[0.60506301 0.33640532 0.91670662 0.25867511]
  [0.18985957 0.85071157 0.4464655  0.05015824]]

 [[0.31437216 0.4410844  0.3256406  0.86501876]
  [0.56335691 0.10591484 0.3902151  0.52558224]]

 [[0.86385615 0.47053712 0.1559594  0.75612186]
  [0.13362915 0.64568854 0.33283032 0.7761046 ]]]


In [21]:
'''
Se o caso desejado forem números inteiros, 
também é possível, desta vez com 'random.randint',
passando os limites desejados
'''
array_aleatorio_inteiro = np.random.randint(-100,100, size=(2,9,9))
print(array_aleatorio_inteiro)

[[[ -84   83  -53    8  -21  -74   91   22   50]
  [  99   -7  -41   92   52  -50   89  -61   36]
  [ -79  -67   13  -11  -19   19  -91   32  -57]
  [ -77   98   41  -24  -52  -61  -53   90   14]
  [   0  -62    6   38   51   89  -62   24 -100]
  [  48  -95  -35   51  -41  -91  -67  -47  -51]
  [  22   26   27   89   77  -97   -1   -5   11]
  [  32  -54   42  -18   70  -59  -98    0  -90]
  [  -3  -66 -100  -45  -68  -27  -76   79  -99]]

 [[ -50   57   10   49   43   80   49   48  -48]
  [  51   93   35  -25   58    2   52   99   -2]
  [  59   35   75   22   98   48   37   43  -65]
  [ -77   59  -15   31   13   62    7  -28  -29]
  [ -99  -54  -87   51   74  -88   62   12  -60]
  [ -73   35  -90   75   44  -14  -38   67  -15]
  [  69  -93   27   75  -55  -82   47  -64  -67]
  [  56   52  -41   22   60  -99   -2    1   -5]
  [ -56   71   56   24  -13  -92   10   -9   47]]]


In [23]:
'''
A matriz identidade também pode ser
facilmente criada, através da função 'identity'
'''
array_identidade = np.identity(5)
print(array_identidade)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
'''
Quando o desejo for copiar um array,
usa-se a função 'copy', porque uma simples declaração não cria cópia
'''
array_copia = np.copy(array_identidade)
print(array_copia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
'''
Caso o array_copia seja alterado,
o array original não é alterado
'''
array_copia[0] = -1
print('Cópia: \n', array_copia)
print('Original: \n', array_identidade)

Cópia: 
 [[-1. -1. -1. -1. -1.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
Original: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
