<a href="https://colab.research.google.com/github/ricardodhuelsmann/python_bibliotecas/blob/main/Introdu%C3%A7%C3%A3o%20ao%20NumPy/4_Matem%C3%A1tica_b%C3%A1sica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
###Operações matemáticas básicas com a biblioteca NumPy


In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [7]:
'''
As operações matemáticas com
NumPy são simples e diretas,
aplicando-se para cada elemento
'''
array_soma = array + 10 #Soma 10 a cada elemento
print('Soma 10: \n', array_soma)

array_multiplicacao = array*3 #Multiplica os elementos por 3
print('Multiplica por 3:\n', array_multiplicacao)

array_quadrado = array**2 #Eleva valores ao quadrado
print('Eleva ao quadrado:\n', array_quadrado)


Soma 10: 
 [11 12 13 14]
Multiplica por 3:
 [ 3  6  9 12]
Eleva ao quadrado:
 [ 1  4  9 16]


In [11]:
'''
Funções trigonométricas também são aplicáveis
'''
array_seno = np.sin(array) #Seno
print(array_seno)

array_cosseno = np.cos(array) #Cosseno
print(array_cosseno)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [16]:
'''
É possível também fazer operações entre 
os valores de duas matrizes
'''
array_2 = np.array([0,1,2,3])
array_3 = array + array_2
print(f'{array} + {array_2} = {array_3}')

[1 2 3 4] + [0 1 2 3] = [1 3 5 7]


In [17]:
array_4 = array * array_2
print(f'{array} * {array_2} = {array_4}')


[1 2 3 4] * [0 1 2 3] = [ 0  2  6 12]
