<a href="https://colab.research.google.com/github/ricardodhuelsmann/python_bibliotecas/blob/main/Introdu%C3%A7%C3%A3o%20ao%20NumPy/5_%C3%81lgebra_Linear_e_Estat%C3%ADstica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
###Aplicações de Álgebra Linear com a biblioteca NumPy

In [2]:
import numpy as np

In [6]:
'''
A multiplicação de matrizes é
comum em Álgebra Linear
'''
array_1 = np.ones((2,4))
print(array_1)

array_2 = np.full((4,2), 2)
print(array_2)

array_3 = np.dot(array_1, array_2)
print(array_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]]
[[8. 8.]
 [8. 8.]]


In [9]:
'''
NumPy permite calcular também 
o determinante de matrizes
'''
determinante = np.linalg.det(array_3)
print(f'O determinante do array_3 é {determinante}.')

O determinante do array_3 é 0.0.


In [16]:
'''
Também é possível encontrar a inversa
de determinada matriz
'''
array_4 = np.array([[0.25,1], [0.5,3]])
inversa = np.linalg.inv(array_4)
print(inversa)

[[12. -4.]
 [-2.  1.]]


###Aplicações estatísticas com NumPy

In [20]:
array_5 = np.array([[0,1,2,3], [4,5,6,7]])
print(array_5)

[[0 1 2 3]
 [4 5 6 7]]


In [21]:
''' 
É possível encontrar o valor 
mínimo e máximo facilmente
'''
minimo = np.min(array_5)
maximo = np.max(array_5)
print(f'O valor mínimo é {minimo} e o máximo é {maximo}.')

O valor mínimo é 0 e o máximo é 7.


In [23]:
'''
É possível encontrar os mínimos por eixos
'''
minimo_linha = np.min(array_5, axis=1)
maximo_linha = np.max(array_5, axis=1)
print(f'O valor mínimo por linha é {minimo_linha} e o máximo é {maximo_linha}.')

O valor mínimo por linha é [0 4] e o máximo é [3 7].


In [24]:
'''
É possível encontrar os mínimos por eixos
'''
minimo_coluna = np.min(array_5, axis=0)
maximo_coluna = np.max(array_5, axis=0)
print(f'O valor mínimo por coluna é {minimo_coluna} e o máximo é {maximo_coluna}.')

O valor mínimo por coluna é [0 1 2 3] e o máximo é [4 5 6 7].


In [25]:
'''
Para determinar a soma dos valores 
dos dados é possível usar 'sum'
'''
soma = np.sum(array_5)
print(soma)

28


In [29]:
'''
Também é possível delimitar os eixos
e encontrar a soma respectiva
'''
soma_linha = np.sum(array_5, axis=1)
print('Soma por linha = ', soma_linha)

soma_coluna = np.sum(array_5, axis=0)
print('Soma por coluna = ', soma_coluna)

Soma por linha =  [ 6 22]
Soma por coluna =  [ 4  6  8 10]


In [30]:
'''
A média é outra função importante
'''
media = np.average(array_5)
print(media)

3.5


In [32]:
'''
De mesma forma como os anteriores, 
é possível fazer por eixos (linha/coluna)
'''
media_linha = np.average(array_5, axis=1)
print('Média por linha = ', media_linha)

media_coluna = np.average(array_5, axis=0)
print('Média por coluna = ', media_coluna)

Média por linha =  [1.5 5.5]
Média por coluna =  [2. 3. 4. 5.]
