<a href="https://colab.research.google.com/github/ricardodhuelsmann/python_bibliotecas/blob/main/Introdu%C3%A7%C3%A3o%20ao%20NumPy/6_Reorganiza%C3%A7%C3%A3o_de_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
###Alteração de forma, inserção de linhas e colunas

In [1]:
import numpy as np

In [15]:
'''
É possível alterar a forma de 
determinado array com a função 'reshape'
Obviamente, o número de dados deve ser respeitado
'''
array_1 = np.array([1,2,3,4,5,6,7,8])
print(array_1)
array_2 = array_1.reshape((2,4))
print(array_2)
array_3 = array_1.reshape((2,2,2))
print(array_3)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
'''
É possível unir arrays usando o 
empilhamento vertical ou horizontal
'''
array_4 = np.ones(8, dtype='int16')
print('Array 1 = ', array_1)
print('Array 4 = ',array_4)
array_5 = np.vstack([array_1, array_4])
print('Empilhamento vertical = \n', array_5)
array_6 = np.hstack([array_1, array_4])
print('Empilhamento horizontal = \n', array_6)

Array 1 =  [1 2 3 4 5 6 7 8]
Array 4 =  [1 1 1 1 1 1 1 1]
Empilhamento vertical = 
 [[1 2 3 4 5 6 7 8]
 [1 1 1 1 1 1 1 1]]
Empilhamento horizontal = 
 [1 2 3 4 5 6 7 8 1 1 1 1 1 1 1 1]
