<a href="https://colab.research.google.com/github/ricardodhuelsmann/python_bibliotecas/blob/main/Introdu%C3%A7%C3%A3o%20ao%20NumPy/7_Carregar_exportar_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
###Carregamento de dados de arquivos .txt e .csv

In [1]:
import numpy as np

In [4]:
'''
Para carregar dados externos
de arquivos como txt, usa-se a 
função 'genfromtext'
'''
dados_txt = np.genfromtxt('dados_txt.txt', delimiter=',')
print(dados_txt)

[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]]


In [5]:
'''
Para importar dados em determinado
tipo, usa-se 'astype'
'''
dados_txt = dados_txt.astype('int16')
print(dados_txt)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]


In [9]:
'''
Processo similar é usado para 
carregar dados de '.csv'
'''
dados_csv = np.genfromtxt('dados_csv.csv', delimiter=',').astype('int32') #Já convertendo diretamente os dados para tipo inteiro
print(dados_csv)

[[ 0 -1 -2 -3 -4 -5 -6]
 [ 9 10 11 12 13 14 15]]


In [23]:
'''
Para exportar determinados dados, faz-se
uso da função 'savetxt'
'''
dados_finais = np.vstack([dados_txt, dados_csv])*2 #Exemplo arbitrário de novos dados ainda não salvos externamente
print(dados_finais)
np.savetxt('dados_finais.txt', dados_finais, fmt='%.i', delimiter=',') #fmt é formatar, no caso, para int
np.savetxt('dados_finais.csv', dados_finais, fmt='%.i', delimiter=';') #outro exemplo, salvando em .csv com outro delimitador

[[  0   2   4   6   8  10  12]
 [ 14  16  18  20  22  24  26]
 [  0  -2  -4  -6  -8 -10 -12]
 [ 18  20  22  24  26  28  30]]
