<a href="https://colab.research.google.com/github/ricardodhuelsmann/python_bibliotecas/blob/main/Introdu%C3%A7%C3%A3o%20ao%20NumPy/Introdu%C3%A7%C3%A3o_ao_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#NumPy
##Exemplos básicos de funcionamento da biblioteca.

In [27]:
''' 
Geralmente faz-se a importação da biblioteca como 'np' 
para facilitar a digitação dos códigos. 
É um padrão internacional entre os programadores
'''
import numpy as np

###Inicializando um *array*

In [28]:
'''
Para criar um array, basta instanciar o nome da variável,
passando uma lista dentro de 'np.array()'
'''
array_1 = np.array([0, 1, 2])
print(array_1)

[0 1 2]


In [29]:
'''
Para criar array de mais dimensões, o processo é semelhante,
mantendo um colchete externo as listas
'''
array_2 = np.array([[2,3,4], [5,6,7]])
print(array_2)

[[2 3 4]
 [5 6 7]]


In [36]:
'''
É possível definir o tipo de dado a ser 
armazenado no array, passando em sua inicialização
informações 'dtype'
'''
array_3 = np.array([[[0,0,0], [1,1,1]], [[2,2,2], [3,3,3]]], dtype='float64')
print(array_3)

[[[0. 0. 0.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [3. 3. 3.]]]


##Obtendo informações dos *arrays*

In [37]:
'''
Para obter informações da dimensão do conjunto,
usa-se a função 'ndim'
'''
print(f'A dimensão do primeiro array é {array_1.ndim}.')
print(f'A dimensão do segundo array é {array_2.ndim}.')
print(f'A dimensão do terceiro array é {array_3.ndim}.')

A dimensão do primeiro array é 1.
A dimensão do segundo array é 2.
A dimensão do terceiro array é 3.


In [38]:
'''
Para obter informações da forma do conjunto,
usa-se a função 'shape'
'''
print(f'A forma do primeiro array é {array_1.shape}.')
print(f'A forma do segundo array é {array_2.shape}.')
print(f'A forma do terceiro array é {array_3.shape}.')

A forma do primeiro array é (3,).
A forma do segundo array é (2, 3).
A forma do terceiro array é (2, 2, 3).


In [39]:
'''
Quando o objetivo é conhecer o tipo de dados
armazenados no array, é possível usar o 'dtype'
'''
print(f'O tipo de dados do primeiro array é {array_1.dtype}.')
print(f'O tipo de dados do segundo array é {array_2.dtype}.')
print(f'O tipo de dados do terceiro array é {array_3.dtype}.')

O tipo de dados do primeiro array é int64.
O tipo de dados do segundo array é int64.
O tipo de dados do terceiro array é float64.


In [40]:
'''
Para conhecer o tamanho (quantidade de dados)
do array, faz-se uso da função 'size'
'''
print(f'O tamanho do primeiro array é {array_1.size}.')
print(f'O tamanho do segundo array é {array_2.size}.')
print(f'O tamanho do terceiro array é {array_3.size}.')

O tamanho do primeiro array é 3.
O tamanho do segundo array é 6.
O tamanho do terceiro array é 12.


In [41]:
'''
Já para conhecer o tamanho (em bytes)
de dados do array, faz-se uso da função 'itemsize'
'''
print(f'O tamanho do dado do primeiro array é {array_1.itemsize}.')
print(f'O tamanho do dado do segundo array é {array_2.itemsize}.')
print(f'O tamanho do dado do terceiro array é {array_3.itemsize}.')

O tamanho do dado do primeiro array é 8.
O tamanho do dado do segundo array é 8.
O tamanho do dado do terceiro array é 8.


In [42]:
'''
Por fim para conhecer o tamanho (em bytes)
do array completo, usa-se da função 'nbytes'
'''
print(f'O tamanho dos dados do primeiro array é {array_1.nbytes}.')
print(f'O tamanho dos dados do segundo array é {array_2.nbytes}.')
print(f'O tamanho dos dados do terceiro array é {array_3.nbytes}.')

O tamanho dos dados do primeiro array é 24.
O tamanho dos dados do segundo array é 48.
O tamanho dos dados do terceiro array é 96.
